services:
  backend:
    build: ./backend
    volumes:
      - ./backend/pdfs:/app/pdfs
      - ./backend/pdfs_images:/app/pdfs_images
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "443:80"
    depends_on:
      - backend
    restart: unless-stopped